#' Visualize Somatic Alterations of fresh frozen Spatial Transcriptomics Data
#'
#' @param files A vector containing file path of spatial barcode txt files
#' @param data1 filtered_feature_bc.csv generated by spaceranger
#' @param data2 Graph-Based csv file exported from 10X Loupe Browser when open Loupe.Loupe
#' @param path Path to the tissue_positions_list.csv under spatial/ folder
#'
#' @importFrom stringr str_replace str_split
#' @importFrom dplyr filter %>%
#' @importFrom utils read.csv read.table
#'
#' @return A list of two dataframe
#' @export
#'
#' @examples \dontrun{
#' files <- list.files(path = system.file("extdata/spotIndex",package = "stmut"),
#'     pattern = ".txt", full.names = TRUE, recursive = FALSE)
#' data1 <- read.csv(system.file("extdata/","filtered_feature_bc.csv",
#'     package = "stmut"), header = TRUE)
#' data2 <- read.csv(system.file("extdata/","Graph-Based.csv", package = "stmut"), header = TRUE)
#' path <- system.file("extdata/","tissue_positions_list.csv", package = "stmut")
#' df <- sptBClstRds(files=files,data1=data1, data2=data2, path=path)
#' }
sptBClstRds <- function(files,data1, data2, path){
  stopifnot(is.character(files), is.data.frame(data1), is.data.frame(data2), is.character(path))

  barcode <- NULL # this code to avoid the note "no visible binding for global variable ‘barcode’"
  nrow <- length(colnames(data1)[-1])

  # Count total reads of each spot
  data1 <- data1[,-1]
  df0 <- data.frame(colnames(data1),colSums(data1)) # spotBcode and total reads of each spot
  colnames(df0) <- c("barcode", "TotalRDs")
  df0$barcode <- str_replace(df0$barcode,".1","-1")
  df1 <- data.frame(matrix(nrow = nrow, ncol = 2))
  lapply(files, function(x){
    tab <- read.table(x, sep = "\t", header = FALSE)
    spts <- str_split(x,"/", simplify = TRUE)
    spts <- str_split(x,"/", simplify = TRUE)[length(spts)]
    sptn <- substr(spts,1,(nchar(spts)-4))
    i <- as.numeric(substr(sptn,5,nchar(spts))) + 1
    df1[i,1] <<- tab[1,1]
    df1[i,2] <<- sptn
  })
  colnames(df1) <- c("barcode","spot")
  df1 <- merge(df1, df0, by = "barcode")

  # generate barcode-spotName-cluster dataframe
  colnames(data2) <- c("barcode","cluster")
  df2 <- merge(data2,df1, by = "barcode")

  # add spot coordinates
  spotloc <- read.csv(path, header = FALSE)
  colnames(spotloc) <- c("barcode","in_tissue","array_row","array_col","pxl_row_in_fullres","pxl_col_in_fullres")
  spotloc <- spotloc[,c(1,3,4)]
  spotloc <- spotloc %>% filter(barcode %in% df2$barcode)
  df2 <- merge(df2, spotloc, by = "barcode")
  returnList <- list(df1, df2)

  return(returnList)
}







#' Count Ref and Mutant Reads for Each Spot
#'
#' @param index A Dataframe of spatial barcode
#' @param files Vector of paths of samtools Mpileup output of each spot
#'
#' @importFrom utils read.delim
#'
#' @return A list of two dataframe
#' @export
#'
#' @examples \dontrun{
#' index <- read.csv(system.file("extdata/","spotBC.csv", package = "stmut"), header = TRUE)
#' files2 <- list.files(path = system.file("extdata/mpileup", package = "stmut"),
#'     pattern = "MpileupOutput_RNA.txt", full.names = TRUE, recursive = TRUE, include.dirs = TRUE)
#' }
#'
sptMutCt <- function(index, files){

  stopifnot(is.character(files), is.data.frame(index))
  Rcount <- NULL

  nr = dim(index)[1] # how many spots
  groups <- rep(0,nr)
  matx <- data.frame(matrix(nrow = nr, ncol = 6))
  colnames(matx) <- c("spot","RreadC", "MreadC","Treads","groups","barcode")

  lapply(files, function(x){

    # extract spot name
    sptNs <- str_split(x, "/", simplify = TRUE)
    idx <- pmatch("spot", sptNs) # partial match
    sptN <- sptNs[idx]
    i <- as.numeric(substr(sptN,5, nchar(sptN))) + 1 # the number of spot;spot name starts with 0000, r start with 1

    # read the Mpileup file
    spot <- read.delim(x, header = FALSE, sep = "\t", quote = "")
    spot[1,9] <- "Rcount"
    spot[1,10] <- "Mcount"
    cn <- spot[1,] # extract column name
    spt <- spot[-1,]
    colnames(spt) <- cn
    spt <- spt[,c(9,10)]
    df <- spt %>% filter(! Rcount == "Manually Inspect") %>% filter(! Rcount == "Manually Inspect")
    df$Rcount <- as.numeric(df$Rcount)
    df$Mcount <- as.numeric(df$Mcount)

    a <- sum(df$Rcount)
    b <- sum(df$Mcount)

    #matx[i,1] <- spots[i]
    matx[i,1] <<- sptN
    matx[i,2] <<- a
    matx[i,3] <<- b
    matx[i,4] <<- a + b
    matx[i,6] <<- index[which(index$spot == sptN),1]

    # add group name for Loupe browser
    if (matx[i,4] == 0){
      matx[i,5] <<- "G0"
    }else if (matx[i,4] == 1){
      matx[i,5] <<- "G1"
    }else if(matx[i,4]==2){
      matx[i,5] <<- "G2"
    }else if(matx[i,4]==3){
      matx[i,5] <<- "G3"
    }else if(matx[i,4]==4){
      matx[i,5] <<- "G4"
    }else if(matx[i,4]==5){
      matx[i,5] <<- "G5"
    }else if(matx[i,4]==6){
      matx[i,5] <<- "G6"
    }else if(matx[i,4]==7){
      matx[i,5] <<- "G7"
    }else if(matx[i,4]==8){
      matx[i,5] <<- "G8"
    }else if(matx[i,4]==9){
      matx[i,5] <<- "G9"
    } else {
      matx[i,5] <<- "G10"
    }
  })

  final <- matx[order(matx$MreadC, decreasing = TRUE),]
  LoupeFile <- final[,c(6,5)]
  colnames(LoupeFile) <- c("index", "groups")
  returnList <- list(final,LoupeFile)
}



